- hosts: all
  connection: local

  vars:
    downloads: ~/.ansible-downloads/
    user_home: "{{ lookup('env','HOME') }}"
    npm_path: ~/.node/bin/npm

  roles:
    - { role: yaegashi.blockinfile, tags: [vagrant,vm,dev] }
    - { role: apps/nodejs, tags: [nodejs,dev] }

  pre_tasks:
    - name: Create ~/.ssh folder
      file: path=~/.ssh state=directory

    - name: Create Ansible downloads directory
      file: path={{ downloads }} state=directory
